Improved awesome testing wrapper

diff --git a/bin/awesome-xephyr b/bin/awesome-xephyr
--- a/bin/awesome-xephyr
+++ b/bin/awesome-xephyr
@@ -1,16 +1,37 @@
-#!/bin/sh 
+#!/bin/sh
 
-display=":42"
+display=":42" # I hope this display is free
+ssize="1024x768"
 
-if [ -n "$1" ]; then 
+if [ -n "$1" ]; then
+	# Use config provided in parameter
     config="$1"
-else 
-    config="$HOME/.config/awesome/test.lua"
+else
+	# Try to find my usual test config
+	test_config="$HOME/.config/awesome/test.lua"
+	if [ -f "$test_config" ]; then
+		config="$test_config"
+	else
+		# Fallback
+		echo "$test_config doesn't exist, assuming default"
+		config="$HOME/.config/awesome/rc.lua"
+	fi
 fi
 
-Xephyr "$display" -screen 1024x768 & 
-export DISPLAY="$display" 
-echo "DISPLAY inside Xephyr: $DISPLAY" 
-sleep 2 
-awesome -c "$config" & 
+Xephyr "$display" -screen "$ssize" &
+xephyr_pid="$!"
+
+export DISPLAY="$display"
+echo "DISPLAY inside Xephyr: $DISPLAY"
+echo "Using $config"
+awesome -k "$config"
+
+if [ "$?" -eq 1 ]; then
+	echo "Syntax check failed, exiting"
+	kill "$xephyr_pid"
+	exit 1
+else
+	awesome -c "$config" &
+	exit 0
+fi
 
