=repo: expand tabs;

diff --git a/bin/rdp b/bin/rdp
--- a/bin/rdp
+++ b/bin/rdp
@@ -7,60 +7,60 @@ stored="$HOME/.rdp-stored"
 sharepath="$HOME/work/winshare"
 
 if [[ -z "$1" ]]; then
-	echo "Host missing"
-	exit 1
+    echo "Host missing"
+    exit 1
 fi
 
 if ! [[ -e "$stored" ]]; then
-	echo "Config $stored missing"
-	exit 2
+    echo "Config $stored missing"
+    exit 2
 fi
 
 arg1="$1"
 
 while read line; do
 
-	if [[ -z "$line" || ${line:0:1} == '#' ]]; then
-		continue
-	fi
+    if [[ -z "$line" || ${line:0:1} == '#' ]]; then
+        continue
+    fi
 
-	if [[ -n "$host" && -n "$login" && -n "$password" ]]; then
-		break
-	fi
+    if [[ -n "$host" && -n "$login" && -n "$password" ]]; then
+        break
+    fi
 
-	key=`echo "$line" | cut -f 1 -d ' '`
-	val=`echo "$line" | cut -f 2 -d ' '`
+    key=`echo "$line" | cut -f 1 -d ' '`
+    val=`echo "$line" | cut -f 2 -d ' '`
 
-	case "$key" in
-		"name")
-			if [[ "$arg1" == "$val" ]]; then
-				name="$val"
-			fi
-			;;
-		"host")
-			if [[ -z "$host" ]]; then
-				if [[ -n "$name" || "$val" == "$arg1"  ]]; then
-					host="$val"
-				fi
-				if [[ "$val" == '*' ]]; then
-					host="$arg1"
-				fi
-			fi
-			;;
-		"login")
-			if [[ -n "$host" ]]; then
-				login="$val"
-			fi
-			;;
-		"password")
-			if [[ -n "$host" ]]; then
-				password="$val"
-			fi
-			;;
-		*)
-			echo "Unknown key: $key"
-			exit 3
-	esac
+    case "$key" in
+        "name")
+            if [[ "$arg1" == "$val" ]]; then
+                name="$val"
+            fi
+            ;;
+        "host")
+            if [[ -z "$host" ]]; then
+                if [[ -n "$name" || "$val" == "$arg1"  ]]; then
+                    host="$val"
+                fi
+                if [[ "$val" == '*' ]]; then
+                    host="$arg1"
+                fi
+            fi
+            ;;
+        "login")
+            if [[ -n "$host" ]]; then
+                login="$val"
+            fi
+            ;;
+        "password")
+            if [[ -n "$host" ]]; then
+                password="$val"
+            fi
+            ;;
+        *)
+            echo "Unknown key: $key"
+            exit 3
+    esac
 
 done < "$stored"
 
